- name: install ntp server
  hosts: ntp_server
  gather_facts: False
  tasks:
  - name: stop chronyd
    shell: systemctl stop chronyd.service && systemctl disable chronyd.service
    ignore_errors: yes
  - name: install ntp
    shell: yum -y install ntp
#    when: ansible_distribution == "CentOS" or ansible_distribution == "openEluer" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Kylin Linux Advanced Server"
#  - name: ubuntu install ntp
#    shell: apt-get update && apt-get install -y ntp
#    when: ansible_distribution == "Ubuntu"
  - name: config ntp.conf
    replace:
     path: /etc/ntp.conf
     regexp: 'server '
     replace: '#server '
#    when: ansible_distribution == "CentOS" or ansible_distribution == "openEluer" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Kylin Linux Advanced Server"
  - name: config ntp.conf
    blockinfile:
     dest: /etc/ntp.conf
     marker: "#{mark}config"
     block: |
      server 127.127.1.0 iburst
      restrict default kod nomodify notrap nopeer noquery
#    when: ansible_distribution == "CentOS" or ansible_distribution == "openEluer" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Kylin Linux Advanced Server"
#  - name: ubuntu config ntp.conf
#    replace:
#     path: /etc/ntp.conf
#     regexp: 'pool '
#     replace: '#pool '
#    when: ansible_distribution == "Ubuntu"
#  - name: ubuntu config ntp.conf
#    blockinfile:
#     dest: /etc/ntp.conf
#     marker: "#{mark}config"
#     block: |
#      server 127.127.1.0 iburst
#      restrict default kod nomodify notrap nopeer noquery
#      server 0.uk.pool.ntp.org iburst
#      server 1.uk.pool.ntp.org iburst
#      server 2.uk.pool.ntp.org iburst
#      server 3.uk.pool.ntp.org iburst
#      server 127.127.1.0 #local clock
#      fudge 127.127.1.0 stratum 10
#    when: ansible_distribution == "Ubuntu"
  - name: restart ntp
    shell: systemctl restart ntpd.service && systemctl enable ntpd.service
#    when: ansible_distribution == "CentOS" or ansible_distribution == "openEluer" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Kylin Linux Advanced Server"
#  - name: ubuntu restart ntpd
#    shell: systemctl restart ntp.service && systemctl enable ntp.service
#    when: ansible_distribution == "Ubuntu"
    
